version: '3'

services:
  web:
    image: franisulla/innorussian:1.0
    container_name: web
    ports:
      - "3000:3000"
    external_links:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30


  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
