enum DITags {
    CLIENT = "CLIENT",
    REFRESH_TOKEN = "REFRESH_TOKEN",
    AUTH = "AUTH",
    SCHEMA = "SCHEMA",
    EMAIL = "EMAIL",
    VERIFICATION_TOKEN = "VERIFICATION_TOKEN",
}

export default DITags;